### ISSUE TITLE
A suggestion for the modpack.

### ISSUE THREAD

**Issue by kraft2004** [imrgr/rise-of-the-pack#1]
Hey, I'm currently playing your modpack, and I am very curious as to if you plan on adding Industrial Foregoing to it or no.
Even if tweaked to be slightly past midgame or something else, it would be a nice addition, unless you want to force players to find some other, harder ways to farm stuff. It is like the good old MFR, so I don't see why not, but I can perfectly understand if you prefer to not add it.

Thanks in advance, 
vini2003.

**Comment by Watschman** [comment]
I would sign the suggestion, it is something I would like as well.

**Comment by imrgr** [comment]
Thank you for your suggestion kraft2004. When Industrial Foregoing first came out I toyed with the idea, but never came to a conclusion. It may be added for the next version, which should hopefully be a full release! Thank you too, Watschman!

**Comment by imrgr** [comment]
1.3.0 is out, and I think you'll both be pleased to find that Industrial Foregoing has been added! Thanks for your feedback!
