### ISSUE TITLE
Minor Visual Glitch/Bug in Questbook

### ISSUE THREAD

**Issue by Watschman** [imrgr/rise-of-the-pack#2]
Pack Version: 1.2.0
Java Version: 8-144 (64bit)
Additional Mods Added: Dimensionloader, Fullscreen Windowed (Borderless) for Minecraft
Type of issue: Glitch/Bug
-------------------------
Hello, 
I am currently playing and streaming your Modpack. 
I noticed that Questchain "Somewhere in the Middle" has a Questline which is out of sight on default 100% View.
![2017-10-22_18 19 24](https://user-images.githubusercontent.com/13834558/31865371-688b7398-b76e-11e7-90ff-5e6151e8d838.png)
I was wondering whether or not this is intended or not, so that the player has to scroll out in order to see the Extra Utilities 2 Questline.

So long, 
Watschman.

**Comment by imrgr** [comment]
Thank you Watschman. In the next version, I will squeeze the quests in this questline together more so that they may show up without scrolling.
