### ISSUE TITLE
Barley Recipe Conflict

### ISSUE THREAD

**Issue by Watschman** [imrgr/rise-of-the-pack#4]
Pack Version: 1.2.0
Java Version: 8-144 (64bit)
Additional Mods Added: Dimensionloader, Fullscreen Windowed (Borderless) for Minecraft
Type of issue: Bug (recipe conflict)
-------------------------
Hello, 
I noticed that Barley(Pam's Harvestcraft) has 2 recipes conflicting with one another. According to JEI, if you put a single Barley into the crafting grid you should get a Barley Seed (For example required in order to function in a Garden Cloche)
![2017-10-30_14 18 22](https://user-images.githubusercontent.com/13834558/32172840-5243bfc2-bd7d-11e7-80a4-26119271b3b4.png)
. But it also has the recipe of 1 Barley to 1 Barley Flour. The latter one takes precedence over the first one,  therefore it is almost impossible to get a Barley Seed at the moment.
![2017-10-30_14 18 34](https://user-images.githubusercontent.com/13834558/32172866-64a1b6c4-bd7d-11e7-9765-6fbe1258284c.png)
 I'd suggest adding a recipe via Minetweaker/Crafttweaker(Or however it is called nowadays) where 2 Barley in the Crafting Grid will give 2 Barley Seeds.
So long, 
Watschman.

**Comment by imrgr** [comment]
Thanks for bringing this to my attention! I have gone with your suggestion of 2 barley = 2 seeds.
