### ISSUE TITLE
Questdetectionbug - Questchain Industrial Foregoing

### ISSUE THREAD

**Issue by Watschman** [imrgr/rise-of-the-pack#7]
Pack Version: 1.3.1
Java Version: 8-144 (64bit)
Additional Mods Added: Fullscreen Windowed (Borderless) for Minecraft
Type of issue: Questbug
-------------------------
Hello, 
In today's stream I noticed a bug in the questchain of industrial foregoing, apparrently the sewage bucket also counts for the pink-slime bucket and meat bucket.
I am not sure whether or not you can change something about that by changing the way the questitems are submitted but I clearly did not create those buckets as you can see here: https://www.twitch.tv/videos/187990352
So far I am enjoying the Pack though.

So long, 
Watschman.

**Comment by imrgr** [comment]
Mr. Watschman,

I can't tell you how grateful I am for how much help you have been giving since starting to play this pack. I know exactly what you're talking about because I ran into this problem as well. I will have to set the quest to check nbt rather than ignoring it.

Thank you!

**Comment by imrgr** [comment]
New version is out! Thanks Watschman!
